---
- name: Install Git
  hosts: all
  become: yes
  tasks:
    - name: Install Git
      apt: name=git state=latest
    - name: Clone a github repository
      git:
        repo: https://github.com/RuslanLesyuk/ruslanlesyuk_resume.git
        dest: /home/lesyukruslan/ruslanlesyuk_resume
        clone: yes
        update: yes
