on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y ansible
      - name: set ansible config secrets
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PRIVATE_KEY_PUB: ${{ secrets.SSH_PRIVATE_KEY_PUB }}
        run: |
          mkdir .ssh
          echo "$SSH_PRIVATE_KEY" > .ssh/my-gcp-web-server
          echo "$SSH_PRIVATE_KEY_PUB" > .ssh/my-gcp-web-server.pub
          chmod 600 .ssh/my-gcp-web-server
          chmod 600 .ssh/my-gcp-web-server.pub
      - name: run exporters playbook
        run: |
          ansible-playbook playbook.yml -i hosts.txt

      
