- name: Play Ansible Playbook
  uses: arillso/action.playbook@master
  with:
    playbook: playbook.yml
    inventory: hosts.txt
  env:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_DEPRECATION_WARNINGS: 'false'
