on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y ansible
      - name: set ansible config secrets
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir .ssh
          ssh-keygen -t rsa -f ~/.ssh/my-gcp-web-server -C lesyukruslan
          sudo chmod 400 ~/.ssh/my-gcp-web-server my-gcp-web-server.pub 
      - name: run exporters playbook
        run: |
          ansible-playbook playbook.yml -i hosts.txt
      
