name: ruslan-lesyuk
env:
 APPLICATION_NAME    : "MyFlask"
 DEPLOY_PACKAGE_NAME : "flask deploy_ver-${{ github.sha}}"
on:
 push:
    branches:
    - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name : Print Hello massage
      run  : echo "Hello World from Testing job"
    - name : Execute few commands
      run : |
        echo "Hello massage 1"
        echo "Hello massage 2"
        echo "Application name: ${{ env.APPLICATION_NAME}}"
         
    - name: Git clone my repo
      uses: actions/checkout@v1
    
    - name: List current folder
      run : ls -la
    
    - name: Lets test some packages if they are here 1
      run : aws --version
      
    - name: Lets test some packages if they are here 2
      run : zip
      
      
  my_deploy:
    runs-on: ubuntu-latest
    
    needs: [my_testing]
    
    env:
    
      VAR1 : "This is Job Level Variable1"
      VAR2 : "This is Job Level Variable2"
    
    steps:
    
    - name: Print Hello Massage
      run : echo "Hello World from Deploy job"
    
    - name: Print env vars
      run : |
        echo "VAR1 = ${{ env.VAR1}}"
        echo "VAR2 = ${{ env.VAR2}}"
        echo "VAR3 = $LOCAL_VAR"
      env:
       LOCAL_VAR: "This is Superr local Environment variable"
     
     
    
    - name: Deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME}}"
