name: Run Ansible playbook

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install Ansible
      run: pip install ansible

    - name: Run chmod
      run: sudo chmod 400 /home/lesyukruslan/.ssh/my-gcp-web-server
      
    - name: Run chmod2
      run: sudo chmod 400 /home/lesyukruslan/.ssh/my-gcp-web-server.pub
     
    - name: Run Ansible playbook
      run: ansible-playbook playbook.yml
      env:
        ANSIBLE_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
