name: Deploy with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/my-gcp-web-server
        chmod 600 ~/.ssh/my-gcp-web-server
        

    - name: Run Ansible playbook
      uses: garygrossgarten/github-actions-ansible@v1
      with:
        playbook: playbook.yml
        inventory: hosts.txt
        become: yes
